### ISSUE TITLE
correct documentation

### ISSUE THREAD

**Issue by BeckeBauer** [Keleo/Fail2BanBundle#1]
nice work, works flawless, thank you!
Just 2 minor suggestions: 
- in your [documentation ](https://www.kimai.org/store/fail2ban-bundle.html) you suggest to name the ```filter = symfony``` in the jail.local. Since you also suggest to name the Kimai specific filter ```#/etc/fail2ban/filter.d/kimai2.conf``` (and not symfony.conf), the filter name has to be ```filter = kimai2``` in the jail.local
- it would be nice to have some hint about the plugin being installed even though there are no options to configure it within Kimai
![screenshot](https://user-images.githubusercontent.com/51003649/61981516-33f6ae00-affa-11e9-9709-9db5fed698be.gif)

**Comment by kevinpapst** [comment]
Thanks for the hints 👍  I only tested the logfile ;-)
Both issues are fixed now, wanna re-test?

**Comment by BeckeBauer** [comment]
jep, no issues left 👍👌

**Comment by kevinpapst** [comment]
Yeah 😁
