### ISSUE TITLE
Failed during configuration: Have not found any log file for kimai2 jail

### ISSUE THREAD

**Issue by canonex** [Keleo/Fail2BanBundle#2]
Debian 10/11
Fail2ban expect a log file:
`/var/www/kimai2/var/log/fail2ban.log`
that, right after install , doesn't exist  (no one has tried to authenticate with wrong credentials yet).

The problem is solved by trying to log in with the wrong credentials once.
It might be helpful to report this in the documentation or create the file.

nb. this is a limitation of fail2ban but it affect the installation process:
https://github.com/fail2ban/fail2ban/issues/1593

Thanks

**Comment by kevinpapst** [comment]
Thanks for the info 👍 

I added a sentence in the docs.
