### ISSUE TITLE
No log file using Docker

### ISSUE THREAD

**Issue by alexanderharm** [Keleo/Fail2BanBundle#8]
I'm using `kimai/kimai2` Docker image and downloaded v2 of the bundle (even though container reports as `1.30.11 stable (Ayumi)`. I installed the plugin (extracted, renamed, rebuild cache, fixed permissions) hopefully correctly at least it shows in the Web-GUI and there are no errors in the log. However, testing it with false logins does not log anything. Neither an error in the existing logs nor anything to `fail2ban.log` (did touch the file and it has the correct permissions). Any ideas where I might have gone wrong?

**Comment by kevinpapst** [comment]
Clarify versions please. Compatibility in the README

<img width="460" alt="Bildschirm­foto 2023-03-29 um 11 25 13" src="https://user-images.githubusercontent.com/533162/228489703-003196ad-e84b-4be7-b972-58a0d0d48c10.png">

**Comment by alexanderharm** [comment]
I installed bundle version 2.0, Docker kimai/kimai2 which reports as `1.30.11` (but should be v2, no?) ...

**Comment by kevinpapst** [comment]
Everything is "v2". Kimai 1 is dead since 2017. You are late to the party...
Bundle 2.0 needs Kimai 2.0. You are running 1.30.11.

**Comment by alexanderharm** [comment]
kimai/kimai2:latest gives you `1.30.11` at least on Docker hub... I just followed this [https://www.kimai.org/documentation/docker.html]() also from the GUI, I'm pretty sure I'm not running v1.

**Comment by kevinpapst** [comment]
SERIOUSLY? AGAIN: Kimai 1 in kimai/kimai1 is dead. Kimai (2) is running in version 1.30.11 on your end.
Kimai 1 vs 2 is not a version number, but a software name.
Kimai (2) in version 2.0 is soon to be released.

**Comment by alexanderharm** [comment]
OK, I'll try with 1.2 then...
